#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Aug 17 21:34:55 2017
hihi
@author: woolseo
"""

import numpy as np
import matplotlib.pyplot as plt
import multiprocessing as proc #insert this line
import time
import datetime


i = 0
N = 2
t_max =100

filename = 'kim 2014 1a xx'

x = 0

def randwalk(k, j, q): #insert q
    
    np.random.seed()
    b = np.random.random((1,3))
    a = np.array([k,j],b)
    
    q.put(a)
    


startTime = time.time()
         
Q = proc.Queue() # queue

p = []

results = np.array([None,2])

for i in range(4):
    
    pp = (i+1)*0.2 
    
    for j in range(10,t_max,10):
            #N번 시행
            for k in range(0, N):
                
                p.append( proc.Process(target = randwalk, args=(k, j, Q)) )
                #p[ k + j*N + j*N*l ].start()
                p[x].start()
                x = x + 1
                results=Q.get(True)
                print(results)
                
            print('end1')
                
            
              




    

print(time.time()-startTime)
